### ISSUE TITLE
Examples crash with OpenRocket 15.03

### ISSUE THREAD

**Issue by SilentSys** [not7cd/orhelper#1]
Does this actually work for you with OpenRocket 15.03?

I tried the example and it very obviously doesn't work --
most of the functions used for startup in the `OpenRocketInstance` constructor seem to no longer exist and belong to an older version of OpenRocket.

Just wondering if this is to be expected or if I'm missing something here...

Cheers.

**Comment by not7cd** [comment]
Good move on your part to fork this. I wasn't successful with this. Good job on openrocket/openrocket#532
